kalpa:
  vars:
    outDir: "/home/vagrant/d2/kalpa-modules/kalpa-mod-gen/out/"
    moduleName: "kalpa-net"
    repo: "git@github.com:patilvinay/kalpa-net.git"
    author: "Vinay Patil"
    email: "vinay.hpatil@gmail.com"
    license: "Apache-2.0"
    initialVersion: "0.0.0"
    git:
      author: "Vinay Patil"
      user: "patilvinay"
      email: "vinay.hpatil@gmail.com"
  __data:
    cwd: "/home/vagrant/d2/kalpa-modules/kalpa-mod-gen"
    bwd: "/home/vagrant/d2/kalpa-modules/kalpa-mod-gen"
  env:
    MAIL: "/var/mail/vagrant"
    USER: "vagrant"
    SSH_CLIENT: "192.168.1.3 50295 22"
    LANGUAGE: "en_US:"
    SHLVL: "3"
    OLDPWD: "/home/vagrant/d2/kalpa-modules/kalpa-mod-gen"
    HOME: "/home/vagrant"
    LOGNAME: "vagrant"
    _: "/usr/bin/kalpa"
    XDG_SESSION_ID: "5"
    PATH: "/usr/bin/gcc-arm-none-eabi-9-2019-q4-major/bin/:/home/vagrant/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin:/usr/bin/gcc-arm-none-eabi-9-2019-q4-major/bin/:/home/vagrant/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"
    XDG_RUNTIME_DIR: "/run/user/1000"
    LANG: "en_US.UTF-8"
    SHELL: "/bin/zsh"
    PWD: "/home/vagrant/d2/kalpa-modules/kalpa-mod-gen"
    SSH_CONNECTION: "192.168.1.3 50295 192.168.1.4 22"
    ZSH: "/home/vagrant/.oh-my-zsh"
    PAGER: "less"
    LESS: "-R"
    LSCOLORS: "Gxfxcxdxbxegedabagacad"
    YSU_VERSION: "1.7.0"
    P9K_SSH: "1"
    AMD_ENTRYPOINT: "vs/server/remoteExtensionHostProcess"
    PIPE_LOGGING: "true"
    VERBOSE_LOGGING: "true"
    VSCODE_IPC_HOOK_CLI: "/tmp/vscode-ipc-4781abda-79c9-480a-abb8-fdc4408cd4e5.sock"
    TERM_PROGRAM: "vscode"
    TERM_PROGRAM_VERSION: "1.45.1"
    COLORTERM: "truecolor"
    VSCODE_GIT_IPC_HANDLE: "/run/user/1000/vscode-git-c7046abb80.sock"
    GIT_ASKPASS: "/home/vagrant/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/git/dist/askpass.sh"
    VSCODE_GIT_ASKPASS_NODE: "/home/vagrant/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/node"
    VSCODE_GIT_ASKPASS_MAIN: "/home/vagrant/.vscode-server/bin/5763d909d5f12fe19f215cbfdd29a91c0fa9208a/extensions/git/dist/askpass-main.js"
    TERM: "xterm-256color"
    P9K_TTY: "old"
    LS_COLORS: "rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:"
